Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using SessionCart.Models;

namespace SessionCart.Controllers
{
    public class CartController : Controller
    {
        private readonly IHttpContextAccessor _contex;

        public CartController(IHttpContextAccessor contex)
        {
            _contex = contex;
        }

        public IActionResult Index()
        {
            List<Order> localOrder = new List<Order>();

            string orderCurrent = _contex.HttpContext.Session.GetString("LocalOrder");
            if (orderCurrent != null)
            {
                localOrder = JsonConvert.DeserializeObject<List<Order>>(orderCurrent);
            }

            string CartQty = "";

            if (string.IsNullOrEmpty(CartQty))
            {
                CartQty = "0";
            }

            CartQty = localOrder.Sum(o => o.OrderProductQty).ToString();

            ViewData["CartQty"] = CartQty;
            ViewData["cart"] = localOrder;

            return View();
        }

        public IActionResult Edit(string id)
        {
            string qty;
            string sifraID;

            sifraID = HttpContext.Request.Form["txtID"].ToString();
            qty = HttpContext.Request.Form["txtKol"].ToString();

            Product product = new Product();
            string localOrderStr;   
            List<Order> localOrder = new List<Order>();

            string previusOrder = _contex.HttpContext.Session.GetString("LocalOrder");
            if (previusOrder != null)
            {
                localOrder = JsonConvert.DeserializeObject<List<Order>>(previusOrder);
            }

            Order foundModel = localOrder.Find(localOrder => localOrder.OrderProductID == sifraID);

            var maxRec = 0;
            string CartQty = "";
            if (localOrder.Count() > 0)
            {
                maxRec = localOrder.Max(a => a.OrderNumberID);
            }

            product.ProductID = foundModel.OrderProductID;
            product.ProductName = foundModel.OrderProductName;

            if (foundModel != null)
            {
                var qtyPrevius = foundModel.OrderProductQty;
                maxRec = foundModel.OrderNumberID;
                int qtyDiff = qtyPrevius + Convert.ToInt32(qty);
                if (qtyDiff == 0)
                {
                    localOrder.Remove(foundModel);
                }
                else
                {
                    localOrder.Remove(foundModel);
                    localOrder.Add(new Order(product.ProductID, product.ProductName, qtyDiff, maxRec));
                }
            }
            else
            {
                maxRec += 1;
                localOrder.Add(new Order(product.ProductID, product.ProductName, 1, maxRec));

            }

            localOrder = localOrder.OrderBy(a => a.OrderNumberID).ToList();

            CartQty = localOrder.Sum(o => o.OrderProductQty).ToString();
            localOrder = localOrder.OrderBy(a => a.OrderNumberID).ToList();

            localOrderStr = JsonConvert.SerializeObject(localOrder);

            _contex.HttpContext.Session.SetString("LocalOrder", localOrderStr);

            if (string.IsNullOrEmpty(CartQty))
            {
                CartQty = "0";
            }

            ViewData["CartQty"] = CartQty;
            ViewData["cart"] = localOrder;

            return View("Index");
        }

        public IActionResult Order()
        {
            List<Order> localOrder = new List<Order>();
            string orderCurrent = _contex.HttpContext.Session.GetString("LocalOrder");
            if (orderCurrent != null)
            {
                localOrder = JsonConvert.DeserializeObject<List<Order>>(orderCurrent);
            }

            foreach (Order po in localOrder.ToList())
            {
                //Add here code to instert order in database
            }

            HttpContext.Session.Remove("LocalOrder");

            return View("Order");
        }

    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SessionCart</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SessionCartAjax.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SessionCart</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index" asp-route-id="">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cart" asp-action="Index">Cart (@ViewData["CartQty"])</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootbox.js/4.4.0/bootbox.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>